library(Seurat)
library(tidyverse)
library(ggplot2)
library(devtools)
devtools::install_github('satijalab/seurat-data')
library(SeuratData)
AvailableData()
install.packages("https://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.0.0.tar.gz", repos = NULL, type = "source")
library(ifnb.SeuratData)
InstallData("ifnb")
data("ifnb")
str(ifnb)
View(ifnb@meta.data)
